### ISSUE TITLE
training error about colmap

### ISSUE THREAD

**Issue by serizawa-04013958** [shreyesss/HDRSplat#2]
Hello, thank you for your great work.
I'd like to train your code by candlefiat, I faced below errors.
do you know how to use training dataset?

`Output folder: /cig/common06nb/deserizk/HDRSplat/output/candlefiat
Optimizing /cig/common06nb/deserizk/HDRSplat/output/candlefiat
/cig/common06nb/deserizk/archive/rawnerf/scenes/candlefiat/sparse [16/10 15:35:51]
demosaic [16/10 15:35:51]

Reading camera 1/52Traceback (most recent call last):
  File "/cig/common06nb/deserizk/HDRSplat/train.py", line 352, in <module>
    training(lp.extract(args), op.extract(args), pp.extract(args), args.render_iterations, args.test_iterations, args.save_iterations, args.checkpoint_iterations, args.start_checkpoint, args.debug_from)
  File "/cig/common06nb/deserizk/HDRSplat/train.py", line 62, in training
    scene = Scene(dataset, gaussians)
  File "/cig/common06nb/deserizk/HDRSplat/scene/__init__.py", line 52, in __init__
    scene_info = self.callback["Colmap"](args.source_path, args.images, args.eval, "demosaic", args.denoise_method)
  File "/cig/common06nb/deserizk/HDRSplat/scene/dataset_readers_raw.py", line 202, in readColmapSceneInfo
    cam_infos_unsorted = readColmapCameras(cam_extrinsics=cam_extrinsics, cam_intrinsics=cam_intrinsics, images_folder=os.path.join(path, reading_img_dir), raw_folder=os.path.join(path, reading_raw_dir),scene_path=path, denoise_method=denoise_method)
  File "/cig/common06nb/deserizk/HDRSplat/scene/dataset_readers_raw.py", line 125, in readColmapCameras
    assert False, "Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!"
AssertionError: Colmap camera model not handled: only undistorted datasets (PINHOLE or SIMPLE_PINHOLE cameras) supported!`

**Comment by shreyesss** [comment]
3DGS implementation only supports simple pinhole camera model for now, to convert the dataset to simple pinhole camera model, install colmap CLI and follow these steps:

$ DATASET_PATH=/path/to/dataset

$ colmap feature_extractor \
   --database_path $DATASET_PATH/database.db \
   --image_path $DATASET_PATH/images

$ colmap exhaustive_matcher \
   --database_path $DATASET_PATH/database.db

$ mkdir $DATASET_PATH/sparse

$ colmap mapper \
    --database_path $DATASET_PATH/database.db \
    --image_path $DATASET_PATH/images \
    --output_path $DATASET_PATH/sparse

$ mkdir $DATASET_PATH/dense

$ colmap image_undistorter \
    --image_path $DATASET_PATH/images \
    --input_path $DATASET_PATH/sparse/0 \
    --output_path $DATASET_PATH/dense \
    --output_type COLMAP \
    --max_image_size 2000
    
    
    For more details refer to: 
    https://colmap.github.io/cli.html
